#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

remote="$(git remote get-url origin)"

url=$(echo "$remote" | cut -d'@' -f 2)
url=$(echo "$url" | tr : /)
url="https://${url}"

echo "> Opening ${url} in browser"

if ! command -v xdg-open &> /dev/null
then
  echo "Could not find xdg-open. Trying python..."
  python -mwebbrowser "$url"  
else
  xdg-open "$url"
fi


